-- MySQL Script generated by MySQL Workbench
-- Sat May 31 12:11:40 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pastebin_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pastebin_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pastebin_db` DEFAULT CHARACTER SET utf8 ;
USE `pastebin_db` ;

-- -----------------------------------------------------
-- Table `pastebin_db`.`buckets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pastebin_db`.`buckets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(16) NOT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `retention_period` VARCHAR(10) NOT NULL,
  `created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `expires_at` TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pastebin_db`.`files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pastebin_db`.`files` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `bucket_id` INT NOT NULL,
  `original_name` VARCHAR(255) NOT NULL,
  `stored_name` VARCHAR(10) NOT NULL,
  `file_size` BIGINT NOT NULL,
  `comment` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `bucket_id_idx` (`bucket_id` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `bucket_id`
    FOREIGN KEY (`bucket_id`)
    REFERENCES `pastebin_db`.`buckets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
